name: qa
dependencies:
    - pip:
        - easydict
        - pyyaml
    - python=3.5.2
    - numpy=1.13.3
    - h5py=2.7.1
    - tensorflow-gpu=0.11
    - nltk=3.2.1
    - tqdm=4.7.4
    - jinja2
    - flask
    - scikit-learn=0.19.1
    - awscli=1.11.120
    - jupyter
channels:
    - conda-forge
    - https://conda.anaconda.org/menpo